"""add guest_id to urls

Revision ID: 9e5929bbdaf0
Revises: 00ed2a17ff7e
Create Date: 2026-08-05 13:15:32.199808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5929bbdaf0'
down_revision: Union[str, Sequence[str], None] = '00ed2a17ff7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_urls_guest_id'), ['guest_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_urls_guest_id'))
        batch_op.drop_column('guest_id')

    # ### end Alembic commands ###
